name: CI
on: [push, pull_request]

jobs:
  test:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        ruby: [ ruby-2.5, ruby-2.6, ruby-2.7, ruby-3.0 ]
        os: [ ubuntu-latest ]

    steps:
      - uses: actions/checkout@v2

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true

      - name: bundle exec rspec
        run: bundle exec rspec --format progress --force-colour

  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7
          bundler-cache: true

      - name: bundle exec rubocop
        run: bundle exec rubocop --format progress --color

      - run: bundle exec rake verify_measurements
